name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - run: |
          sudo apt-get update
          sudo apt-get install coinor-libcbc3 coinor-libclp1 libglpk40
      - run: bundle exec rake test
